### ISSUE TITLE
Fix for libxft error

### ISSUE THREAD

**Issue by Ultrahalf** [mhdzli/mz-dwm#1]
I think you have to install libxft-bgra from aur.

**Comment by mhdzli** [comment]
@Ultrahalf 
I've been using another repository for my build of dwm recently.
You can find it [here](https://github.com/mhdzli/dwm)

**Comment by mhdzli** [comment]
[My new build of dwm](https://github.com/mhdzli/dwm) use libxft-bgra and since I'm using dwm on distributions other than arch and there isn't a fix package for libxft in their repositories I keep this repository unarchived until the fix patch merge to the libxft.
